// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetoRPG.Data;

#nullable disable

namespace ProjetoRPG.Migrations;

[DbContext(typeof(RpgContext))]
partial class RpgContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "9.0.1");

        modelBuilder.Entity("ProjetoRPG.Models.Missao", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<DateOnly?>("DataLimite")
                    .HasColumnType("TEXT");

                b.Property<string>("Descricao")
                    .HasMaxLength(400)
                    .HasColumnType("TEXT");

                b.Property<int>("Dificuldade")
                    .HasColumnType("INTEGER");

                b.Property<int>("RecompensaOuro")
                    .HasColumnType("INTEGER");

                b.Property<int>("Status")
                    .HasColumnType("INTEGER");

                b.Property<string>("Titulo")
                    .IsRequired()
                    .HasMaxLength(120)
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.ToTable("Missoes");
            });

        modelBuilder.Entity("ProjetoRPG.Models.Personagem", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<int>("Classe")
                    .HasColumnType("INTEGER");

                b.Property<int>("Mana")
                    .HasColumnType("INTEGER");

                b.Property<int>("Moral")
                    .HasColumnType("INTEGER");

                b.Property<string>("Nome")
                    .IsRequired()
                    .HasMaxLength(80)
                    .HasColumnType("TEXT");

                b.Property<int>("Nivel")
                    .HasColumnType("INTEGER");

                b.Property<string>("PatenteGuilda")
                    .HasMaxLength(40)
                    .HasColumnType("TEXT");

                b.Property<int>("Vida")
                    .HasColumnType("INTEGER");

                b.HasKey("Id");

                b.ToTable("Personagens");
            });

        modelBuilder.Entity("ProjetoRPG.Models.PersonagemMissao", b =>
            {
                b.Property<int>("PersonagemId")
                    .HasColumnType("INTEGER");

                b.Property<int>("MissaoId")
                    .HasColumnType("INTEGER");

                b.Property<DateTime>("DataAtribuicao")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("TEXT")
                    .HasDefaultValueSql("CURRENT_TIMESTAMP");

                b.Property<string>("FuncaoNoGrupo")
                    .IsRequired()
                    .HasMaxLength(40)
                    .HasColumnType("TEXT");

                b.HasKey("PersonagemId", "MissaoId");

                b.HasIndex("MissaoId");

                b.ToTable("PersonagensMissoes");
            });

        modelBuilder.Entity("ProjetoRPG.Models.PersonagemMissao", b =>
            {
                b.HasOne("ProjetoRPG.Models.Missao", "Missao")
                    .WithMany("Participantes")
                    .HasForeignKey("MissaoId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("ProjetoRPG.Models.Personagem", "Personagem")
                    .WithMany("Missoes")
                    .HasForeignKey("PersonagemId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Missao");

                b.Navigation("Personagem");
            });

        modelBuilder.Entity("ProjetoRPG.Models.Missao", b =>
            {
                b.Navigation("Participantes");
            });

        modelBuilder.Entity("ProjetoRPG.Models.Personagem", b =>
            {
                b.Navigation("Missoes");
            });
#pragma warning restore 612, 618
    }
}
